### ISSUE TITLE
Static function to create fromArray()

### ISSUE THREAD

**Issue by dol** [Crell/ApiProblem#24]
The [acme protocol](https://tools.ietf.org/html/draft-ietf-acme-acme-17) returns in https://tools.ietf.org/html/draft-ietf-acme-acme-17#section-7.1.3 an error object which is in the format of RFC 7807.
To get this informations into a ApiProblem we need to perform a json_decode of the payload. Extract 'error' and json_encode the data to be passed to ApiProblem::fromJson.

It would be easier to just have a static function like decompile named ApiProblem::fromArray() to perform the work.

**Comment by Crell** [comment]
They're actually naming a protcol ACME???

I'm a bit skeptical; from a quick glance it looks like just a portion of the ACME payload is a 7807 string?  Are you suggesting an ACME-parsing function, or just something that is barely a step above deserialize, in essence?

If the latter, I guess I have no particular objection to it and would accept a PR for it.  However, be aware of the refactoring going on in #23 so that you don't bump into it.

**Comment by Crell** [comment]
Ah, OK.  Yeah, I'd take a PR for that.  It looks like it wouldn't conflict with #23 either, which is good.

**Comment by dol** [comment]
If you give me some time I'll add some tests as well. Was only a PoC.

**Comment by Crell** [comment]
Hey @dol.  Are you going to be following up on this issue or shall I close it?

**Comment by datashaman** [comment]
[decompile](https://github.com/Crell/ApiProblem/blob/master/src/ApiProblem.php#L197) is that method. Rename it and make it public, solved.
